# This rule is not used by the project cronjob-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to batch.whitea.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cronjob-controller
    app.kubernetes.io/managed-by: kustomize
  name: cronjob-viewer-role
rules:
- apiGroups:
  - batch.whitea.com
  resources:
  - cronjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch.whitea.com
  resources:
  - cronjobs/status
  verbs:
  - get
